# This is a basic workflow to help you get started with Actions

name: CI Deploy

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        type: environment
        required: true
        options:
        - staging
        - production
jobs:
  deploy-by-environment:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - run: |
          echo "Environment: $ENVIRONMENT"
        env:
          ENVIRONMENT: ${{ inputs.environment }}
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: readmeio/rdme@7.2.0
        with:
          rdme: openapi swagger.prod.json --key=${{ secrets.README_API_KEY }} --id=${{ secrets.README_API_DEFINITION_ID }}
